language: python
python:
  - '2.7'
install:
  - pip install slackclient
  - pip install urllib3
script: ./unittests
notifications:
  slack:
    secure: jMJ5MLZsVBf9265pj5pnKevZIzcwDwytVbJC9w07i1gNDx1omOE1x+e109i/8MBY9Rt4bUvHDCkZ9eDRnviIXmQBx0D1vAbOGrsCn1/BJaauqjldxlkGo0B7GbVO5dDZQFkkbxhMSwjHhA5RDBsAQ+oOMVJaSl82EIbfEwA7fNsgYB7iwZqiS6qUZt8nSeg7ZT52gh7hQs2rbTvQFQwHFgJnAGVyjR5IU92c4N8MBr2J7450qBQNA/t4wGipe5kSTfa9QV8xX+FbTM7qn3f0Sx5iElti+xBTKC4WTK4YWJG63fSFaC7LXpmu4pYcTFIxKbiPDZGsf0dm5ecXQsSJ4xJUz+A/tbsI2ZWI8knq328IQ/wGoFG86QTK2Gciz+bFZp+1eQX6kPMwSgqtZ9dUm0Rw/E3wn6SOGkkyggqVMVra5EoF7TBDYs4mbW7Lx4NA1dDzdQ5/Sl0leNwQmHx59s3tntLNM3ZoRLbU/3yJriCs2JyJeLno17C0Uy1rsFj0c3vZKBo3NF8fF5RAKdEenJ0mkmIqfL8z7+HCDjRFtN9jTzua/8KJDU3uYHpgUuStzkX85dkXYIcfIqZ4cTgtGiJ+sb5mL2DanE+h7kS1HRtcMqOsMrjevkIiKorUaQuXQx6t9xm2Hj1wxC2o9xYAWkPRgMRPNJ7kXgSTQeu4ohk=

deploy:
  provider: pypi
  skip_cleanup: true
  user: "wray"
  password:
    secure: uesG3ZpL6lu19RiJBymNaRKwi+mREXo/kuFsP8p0lL1Byh/MkYEbp4xhKKU8R+4MvBJJ9+djZ6ib0s0/Y1gGSL8WhqtKvUOJUQ63DV/YhcPTa6yGFo4CstQjPAj5ITuJ3VgICjvbc4NlX1Y4YMvWgCHt5K/1soFV9zDm7rXIJSYo06+Zi2I06odz5+uTgj5ZCyIhdIE9r2b/IwIEM+kl3EdskSWTsiMp3S222PEE/rYvWsrN/BzS0ShTwPTbO16NZ7vstHtRusfbcyHYj5BgmFpeBOFmbrXmWt9o7oFGAhQ05QGphnuK/0G4+yh9yaT6rqqOga7YL6/MBCcwtuaQSDJFaLXqqH4+IyMCcptuCgWIe++vZ0AN3WPN/A0VJq7YXhWwbaa8m4KPXB4h04jLmKosatbY5rqfkU2KQvknK6AknyF/1kTNPIdbSTw+uCnNFaD1EeFq/lpyXbddryQhlwHvNZiX4zWrRpmuJ+fEltTiEIm5nrneXd/zCCcCjMaS6EmAnLhWqGf5ZFYtF7+vvv25Ty3DcZ4F921Pwtru7jom1uOLm1luqt8UnshdK3gt1bQWpaEkdTtu1afwP/wtq1S81Ix+cgPW7eg2kJrln3B1RVDcQQ90m7Ab/kBSOYapE/WJKt0rbTSXRFvKIlXzYSmFF/0v6+RST2RMbZkZWbw=
